### ISSUE TITLE
Message seems to be sent but not delivered.

### ISSUE THREAD

**Issue by mana99123** [tomer8007/kik-bot-api-unofficial#1]
I tried using your API to send a simple text message to myself using my other accounts credentials in the code, but it says "Message seems to be sent but not delivered." When I was trying to send this message to my original account, my original was online as you said it should be.

**Comment by tomer8007** [comment]
Okay, I'll try this out shortly. But for now, do you receive the message on your original account?
If you look at the code (`kik_client.send_message)`, you can see that this message is printed out when kik's server sends back an acknowledgement of the `message ` stanza, but does not send anything later for exactly one second. Usually when someone is online, the phone will send back a delivery acknowledgment in a short time, so that's why it says "Message seems to be sent but not delivered".

**Comment by tomer8007** [comment]
Thank you for letting me know.
I have fixed this problem and it should be resolved now!

**Comment by mana99123** [comment]
Fixed
