### ISSUE TITLE
Detect mentions 

### ISSUE THREAD

**Issue by Jumvah** [tomer8007/kik-bot-api-unofficial#188]
Be able to detect mentions so something like:

@botname [command]

would send [command] to @botname (even if not in the current gc or pm) and response would be sent back to the gc / pm that made request

**Comment by tomer8007** [comment]
Isn't this something that we should expect bot makers to implement in their bot? Or does it have something to do with kik itself?

**Comment by bluemods** [comment]
From re-reading it, no you cannot have an unofficial bot be called in any group. It has to be in the group / you have to PM it directly for it to work.

**Comment by Sitiaro** [comment]
I've been using this as a replacement and it's been working fine for me. (if you're using a private bot then ofc it won't be accessible by chats that don't have the bot, p sure that you need to get one from dev.kik.com to make that happen for the time being)

prefix='@'


        if chat_message.body.startswith(prefix):
            if chat_message.body.lower() == prefix+"yourbotname help":
                self.client.send_chat_message(chat_message.group_jid, 'help\n -whatever')
                return

**Comment by bluemods** [comment]
I mean sure that's a way to handle bot responses and make sure they want to use your bot, but the OP was asking how to find who was the original user that mentioned an official Kik @bot, since from first glance you only seem to see the @bot's jid in the "from" attribute.

People like to use official bots for things like bypassing spam restrictions, so it's important to know the original mentioner.
