### ISSUE TITLE
Is there an example for group joining?

### ISSUE THREAD

**Issue by shaitjo** [tomer8007/kik-bot-api-unofficial#19]
help_wanted: I want to lurk on a number of conversation in chats.

**Comment by tomer8007** [comment]
Unfortunately not currently.
Maybe I could add that in a week or so.
If you manage to write it yourself it can be very useful for others to paste it here.

**Comment by shaitjo** [comment]
>>write it yourself
If you give me pcap

**Comment by tomer8007** [comment]
I will try to work on that when I'll have the time

**Comment by bardaguera** [comment]
I think method should be like:
```
def join_group(self, jid, code):
    self._log("[+] Join a group: {}".format(code))

    uuid = KikCryptographicUtils.make_kik_uuid()
    data = '<iq type="set" id="{}">' \
           '<query xmlns="kik:groups:admin">' \
           '<g jid="{}" action="join">' \
           '<code>{}</code>' \
           '</g>' \
           '</query>' \it
           '</iq>'.format(uuid, jid, code)

    self._make_request(data)
    response = self._get_response()
```
Unfortunately, I get an error:
[400_error.txt](https://github.com/tomer8007/kik-bot-api-unofficial/files/1681420/400_error.txt)

**Comment by tomer8007** [comment]
Did you take this XML from the wiki?

**Comment by bardaguera** [comment]
I take this xml from captured traffic, which was pretty obvious.
There is no example for group join in wiki, as I can see.

**Comment by tomer8007** [comment]
Yes, I'm sorry for not being able to debug it these days.
I'll see if I can have some time for that tomorrow.

**Comment by edroot** [comment]
Good idea, do this function

**Comment by tomer8007** [comment]
Okay, last weekend I was refactoring and taking care of the 'new' branch.
Next time I'll try working on this function.

**Comment by tomer8007** [comment]
**Update**
I have implemented the methods for joining a group including the token generation.
Unfourtuanely I also get 400 bad request even though everything looks correct. This seems to be a harder problem than I tought.

**Comment by edroot** [comment]
This problem is not on all accounts, but only on those accounts that did not pass the anti-spam check. I'm now trying to understand how this test happens

**Comment by tomer8007** [comment]
Cool, were you able to join a group using the new code when connected to an account that passed the anti-spam check?

**Comment by edroot** [comment]
Yes, If the check for antispam once passed, then joining the group works

**Comment by tomer8007** [comment]
Did you try doing that using the new function I uploaded? If it works, we can remove the comment there that says it doesn't.

I get a 400 bad request error, can you make it return something else?

**Comment by edroot** [comment]
new function work, but only if the account has been verify

**Comment by tomer8007** [comment]
OK, cool.

**Comment by tomer8007** [comment]
How to get an account verified?

**Comment by edroot** [comment]
I have this requests and responses, but understand how make signature? give me you email or skype or telegram id

**Comment by tomer8007** [comment]
I don't understand what do you mean by signature.

**Comment by edroot** [comment]
give me contact i send full session file.
Request first
<iq type="set" id="[kik-uuid]"><query xmlns="kik:auth:cert"><key type="rsa"><der>[kik-pub-key]</der><signature>[??????]</signature></key></query></iq>

**Comment by CheshireCaat** [comment]
How i can verify account? Please show full request/response

**Comment by bluemods** [comment]
I've perfected the kik:auth:cert query, it makes public and private keys that are mainly used for websites (stickers, emote unlocks) and was also set up to be used for message encryption (not sure if E2E or P2P) but it was never actually used by Kik.

Even after getting this step right and the <k tag right (this python client gets it horribly wrong, you can check if it's correct by sending a content message to yourself with the app id of com.kik.ext.camera, if you messed up somewhere Kik will change the app id back to com.kik.ext.gallery when the stanza is recieved) I still can't do anything with groups yet.

Requirements before joining a group:

- <k tag NEEDS to have all attributes correct and more importantly need to be sorted in the correct order (it also needs to have a specific amount of spaces added before the <k tag even starts based on the hash code of the map, and this client completely ignores this so it fails every time)

- SafetyNet not required, but it probably helps (my Blue Kik mod has the safety net request ignored, and most people can join groups)

- I believe there's some HTTP requests also required upon each connect! 

I tested this by logging into unmodded stock Kik and was able to join groups, and then I took the username / device id / version values and sent a <k auth stanza pretending to be like I'm the stock kik app reconnecting, but somehow it blocked everything again when I reauthed, but then when I reopened the stock kik app and it reauths the groups are fixed. 

The main obstacle I believe to be is the Kin HTTP requests. Every time the android app connects, it sends a xiphias stanza with service ```mobile.kin.authentication.v1.Authentication``` and method ```GenerateUserJwt``` with the encoded body being the jid you're signed in with. It then gives a xiphias response with a JWT which is then used to log in with the Kin server. I believe that now this is required before joining groups, unless anyone can tell me otherwise that somehow this client in it's current state can join groups.
