### ISSUE TITLE
Sniffing traffic

### ISSUE THREAD

**Issue by Githubplay12** [tomer8007/kik-bot-api-unofficial#22]
I know this is old and I don't know if you still check this from time to time anyway...

I tried sniffing traffic from the kik api using burp with the NOPE proxy for non http protocols, I installed the burp certificate on my phone, unfortunately it seems KIK messenger is using ssl pinning which I can't remove yet (I didn't start reverse engineering, lazy mofo).

Yet the version you're using for this is the same as I'm using (11.1.1.12 something) and you succeeded at sniffing traffic, so did you have to ssl unpin it or it's not ssl pinned and it's not working for me for some other reason ?

Maybe I should try with MITM or SSLstrip or an older version ?

This is professional work that I admire hence why I'm trying to learn to.

Thanks sir.

**Comment by tomer8007** [comment]
If I'm not wrong I initially thought they use certificate pinning but then it turned out they didn't. at least in the version I was playing with.

But I can say a few things:

1. Did you check Burps's alerts tab ? Usually if an app is trying to pass a TLS connection through burp and it fails, burp lets you know about that it this tab. I have seen this clearly in other apps that do use certificate pinning. But I never used the NOPE extension so I don't know if there's something similar there.
2. Did you try allowing TLS connections transparently? This option does not overwrite the certificate and just does a "pass through". Using this can reveal wether or not they use certificate pinning. Again, not sure if exists in NOPE.
3. You can open up Wireshark and see if there's a TLS handhake rejection there. It's really clear and it's the best way to tell if they rejected burp's fake certificate or not.
4. And yes, you can try SSLstrip. That's what I used.

By the way, I do check this project from time to time. The problem is that I can really get to work on it once in a week or so.

Thank you for exploring this anyway

**Comment by Githubplay12** [comment]
Yea I've seen the alert tab and it shows "False certificate" something along those line.

I don't know how to do that in Burp, I will try and get back to you.

Wireshark is really not friendly I don't like it, too much informations.

I will try with SSLstrip tomorrow.

Thanks for answering sir, to clarify the version of kik you used is 11.1.1.12xxx right?

**Comment by tomer8007** [comment]
In the code I see the version 11.1.1.12218, yeah.

Good luck with SSLsplit, it's not really user friendly but there's a good tutorial for it in the internet.

Oh and I thought about another possibility: I heard that starting from Android 7.0 apps don't trust user-supplied CA certificates anymore. That could explain why Kik is rejecting the fake certificate....

So If you're testing on Android 7, it's definitely worth trying that on Android 6 or googling around to see how to bypass that new limitation (I think you have to add a flag to the apk file and reinstall)

**Comment by Githubplay12** [comment]
I'm not using android 7+ so it's not the problem, I think the problem is that I'm using android and you used an iphone to sniff traffic as in most apps the ssl unpinning in not existant in the IOS version of the app, can you confirm my theory?

**Comment by tomer8007** [comment]
Nope. 
Tested on a Genymotion emulator in OS X 10.9.

Another guess: Are you sure you properly installed the CA? Can you intercept other apps?

**Comment by tomer8007** [comment]
What I can say for sure is that almost certainly they do use certificate pinning in higher versions.
And, after looking a bit at the files I was messing with back then, I have to say they do have a lot of files relating to certificates.
Additionally I found that I was using  kik version 11.18.0.15444, and kik version 11.1.1.12218.zip. Maybe you should try both.

BUT, assuming they do use certificate pinning, you have two options:
1. Try messing with their files or code (I would first try thei `ca_certificates.crt` under res/raw)
2. Try using a patched apk of kik I found on my computer. I'm not quite sure what I patched there, but it could be the certificate pinning logic.
3. Use tools such as [JustTrustMe](https://github.com/Fuzion24/JustTrustMe) which try to disable the pinning logic automatically.
