### ISSUE TITLE
Can I follow the link programmatically?

### ISSUE THREAD

**Issue by CheshireCaat** [tomer8007/kik-bot-api-unofficial#44]
Can I follow the link programmatically?
For example http://kik.me/g/2gW5hq_l11EbfogXIcNB0XGBSH8

**Comment by tomer8007** [comment]
Not right now at least

**Comment by xorist** [comment]
Is the issue here, he is wanting his bot to automatically join (or at least get and return the information for) a link that is pointing at another group/contact?

**Comment by bluemods** [comment]
Easy

invite code is acquired by splitting after the /g/

```http://kik.me/g/2gW5hq_l11EbfogXIcNB0XGBSH8``` -> ```2gW5hq_l11EbfogXIcNB0XGBSH8```

```<iq type="get" id="{}">```
```<query xmlns="kik:groups:admin">```
```<g action="lookup">```
```<invite-code>{}</invite-code>```
```</g>```
```</query>```
```</iq>```

That returns important information about the group, most importantly the jid and the max group size, as Kik does not return the max group size usually but always returns it with this request. Useful for making 100 member groups.

To join group with invite code, first send the above request then send

```<iq type="set" id="{}">```
```<query xmlns="kik:groups:admin">```
```<g jid="{}" action="join">```
```<invite-code type="link">{}</invite-code>```
```</g>```
```</query>```
```</iq>```

JID is the one you got from the lookup request.

Invite code is the one you first used to search with.

It's best to sleep a couple of seconds between getting the result and joining with the invite code because Kik may block it if you don't wait.

The nice thing about this is that group joining with invite codes has no protection, Kik should always allow these even if it thinks you're a bot
