### ISSUE TITLE
Capturing traffic.

### ISSUE THREAD

**Issue by Keln54** [tomer8007/kik-bot-api-unofficial#5]
Hello!

I have locked at you code for Kik API. How do you take endpoint for API? Thats amazing. 
I would like to write kik bot too, but i dont know how can i capture traffic and enpoints. 

Can you help me with this? I will be very grateful!

**Comment by tomer8007** [comment]
To capture traffic I used a man-in-the-middle software that intercepts connections on port 5223 (secure XMPP port). It's called `sslsplit`. Here's a good guide to start with:
https://blog.heckel.xyz/2013/08/04/use-sslsplit-to-transparently-sniff-tls-ssl-connections/
You can also try a more popular software called [mitmproxy](https://mitmproxy.org/).

For this to work you have to make sure that traffic is redirected from your phone to your computer. I used a default gateway configurtion and then something similar to iptables for this to happen. Also, remember that because kik is using XMPP over TLS encryption you have to create a self-singed CA certificate and install it on the phone (to make the kik app trust your computer).

**Comment by Keln54** [comment]
Thanks a lot! I will try to do that. 

After looking your code i have one question: i can't change device id?

**Comment by tomer8007** [comment]
You can change it to whatever you want, I just hard-coded it for experiments.

**Comment by Keln54** [comment]
Okay, gratefull! Do you have plans to make function to send messeges through SOCKS proxy?

**Comment by tomer8007** [comment]
Do you mean like making the python code communicate with kik servers behind a SOCKS proxy? why not just configure it at the OS-level?
Or do you mean reverse-engineering more kik stuff by using a SOCKS proxy instead of the way I did it so far?

**Comment by Keln54** [comment]
I mean communicate with kik servers behind a SOCKS proxy. Well, i can really make with OS-level. I just try to make it myself with pysocksi and have no success :)

**Comment by tomer8007** [comment]
Actually yes, using something like [PySocks](https://github.com/Anorov/PySocks) is a much better idea. I didn't try using it but I think your problem might be realted to the fact this code uses SSL wrapped sockets, and the internet offers quite nice solutions for using those together:
https://stackoverflow.com/questions/16136916/using-socksipy-with-ssl
https://github.com/Anorov/PySocks/issues/29

Maybe it'll work.

**Comment by maritaria** [comment]
Awesome work, I've started transcribing the code to C# for a project on my own. I've also started reverse engineering code from the kik app. Will let you know if I uncover details interresting to you. I've also tried the MITM approach but didn't get it working correctly.

**Comment by tomer8007** [comment]
Cool!

**Comment by maritaria** [comment]
Actually, for the first connection `<k anon="">` is sufficient

**Comment by tomer8007** [comment]
The payload inside `connect_to_kik_server`? Do you mean there is no need to send all the cryptographic parameters in there?

**Comment by tomer8007** [comment]
I wonder why they did that in the official app then. Anyway it's great to know

**Comment by Keln54** [comment]
Hello! I have lost full day trying to capture traffic with mitm. Tomorrow i will try to make it again :) Sorry, i whant ask one thing - i must to forward port 5223 with iptables to listening port in mitm\sslsplit? Or just 443 and 80? May be there is my mistake...

**Comment by tomer8007** [comment]
You should forward port 5223 because that's the port kik uses
